### ISSUE TITLE
Mod Tried to rebind 1 Slot key.

### ISSUE THREAD

**Issue by ZuVEnO** [ClumsyAlien/TimelessandClassics_Reforged#12]
Without:
![Снимок экрана (33)](https://user-images.githubusercontent.com/70200849/141648696-b2297399-8cd9-451d-b340-96406cfe5bc3.png)

With:
![Снимок экрана (34)](https://user-images.githubusercontent.com/70200849/141648719-156edb3e-fc44-4c18-8e22-ec549193b576.png)

**Comment by JukoiDev** [comment]
Yeah i have something like this everytime i play for about 2 minutes.

**Comment by ClumsyAlien** [comment]
Yes, this is due to the addition of the toggle aim function I added, by my understanding having the default set to RMB breaks the number 1 as an input when MC loads settings? It's still unexplained and personally have some difficulty replicating however I did manage to achieve the error once and applied a fix.

Seems like it has gone away in my current builds, and this will be included in the 0.2+ update series releasing in the close future.

**Comment by HenryMaxler** [comment]
Still happening in this version: timeless_and_classics-gun_mod-0.1.4.1-1.16.5.  It's REALLY annoying because even if you set it, it will overwrite it EVERY TIME.  It's too bad though because this gun mod is so great, I wish it didn't affect everything.  I tried to prevent it by setting the default settings with the Default Options mod, but nothing seems to work.

**Comment by DilapidatedMirror** [comment]
The mod is still trying rebind my 1 slot key, this makes me feel unconfortable. Obviously this is an excellent mod but this is really annoying and looks like a drop of black ink dropped on a white paper. I hope the developer of Timeless And Classics can fix this mistake as soon as possible.
这个mod一直在尝试修改我的快捷栏一号键位，这让我感到很不舒服。显而易见的，这是一个非常优秀的mod但这个bug却真的很烦人，就像一滴黑墨水滴在了白纸上一样。我希望Timeless And Classics的开发者可以尽快修复这个错误。

**Comment by ClumsyAlien** [comment]
Update to the latest public version of TaC on Curseforge.
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac
