### ISSUE TITLE
Supressor unbalanced

### ISSUE THREAD

**Issue by JukoiDev** [ClumsyAlien/TimelessandClassics_Reforged#13]
Hi, I am making modpack(private just for me) with this mod(latest REFORGED version), and I think supressor is OP, it's cheap for it's capabilities. You can make the supressor -% volume to something like -30% volume? This will help balance the mod c:

**Comment by JukoiDev** [comment]
Also You can make -1 dmg when using silencer

**Comment by ClumsyAlien** [comment]
This issue is being closed directly, as this is much more of a feature request compared to any serious bug others may run into, we do have Discord were this sort of request is much more appreciated in however I will give you some details right away.

**A.** The suppressor is built compared to the real life, suppressors make a noticeable difference to both sound volume and profile, hence we showcase it in game, for multiplayer this does not help much as sound is still global, and does not decrease over distance, it either exists in the range, or doesn't, same with mobs, reactions from the additional mob AI has reduced range against weapons with suppressors, and to make the attachment at all useful, this was required to be substantial

**B.** We have more barrel attachments, like Muzzle brakes and Compensators, both as well making big differences to a weapons performance when attached, putting a suppressor instead of reducing recoil or increasing accuracy is a big difference, and must be balanced out within the other attachments, if anything suppressors should increase weapon damage if we were to stay realistic, however to maintain some more balance in the earlier versions of the mod, I only increased Critical Hit Chance by +7.5% to simulate the higher velocity gained from a technically longer barrel, and to make the suppressor slightly more worth while in comparison

Any more comments please transition to the Timeless Discord server, where others can also share their opinions along side yours and my own.
