### ISSUE TITLE
tac-release-0.3.10.5-1.16.5.jar is crashing

### ISSUE THREAD

**Issue by Turanus5966** [ClumsyAlien/TimelessandClassics_Reforged#165]
Version tac-release-0.3.10.5-1.16.5.jar is crashing  (as I understand it, it doesn’t work well with Obfuscate)

![Снимок экрана 2023-12-05 202740](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/assets/135041144/fd1aa9bd-11a2-459b-aae6-586158e31aa2) 

(Only two mods: Obfuscate & Timeless and Classic Guns)

![Снимок экрана 2023-12-05 203047](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/assets/135041144/3433b4fa-fd05-40a6-b820-a99fc93ba37c)

**Comment by xjqsh** [comment]
Although you didn't provide a crash report, the situation should be failed to loading resources. Because of some design flaws in the loading of models, this problem may occur on some computers with poor hardware, and you may want to consider trying to remove the dyed skin from the mod assets to get the game to start properly.

**Comment by Turanus5966** [comment]
How to remove a skin from a mod?
