### ISSUE TITLE
Licensing and forking

### ISSUE THREAD

**Issue by qtdyn** [ClumsyAlien/TimelessandClassics_Reforged#86]
Hi, I'd like to fork your mod to modify and redistribute it for a public & commercial modded server, is there a way I can do so? This repository doesn't seem to hold a proper license for the mod (only Forge's).

Thanks!

**Comment by ClumsyAlien** [comment]
I would rather you have a direct contact with the team and I for discussing this, there is a license and it is the same 
https://github.com/ClumsyAlien/TimelessandClassics_Reforged/blob/1.16.X/LICENSE-new.txt
The fork must A: be public, and B: have a different name externally and internally. Since your project is separate of both CGM and TaC, and isn't official for either.
